blank_issues_enabled: false
version: 2.1
contact_links:
  - name: ğŸ¤— PyPOTS Community on Slack
    url: https://join.slack.com/t/pypots-org/shared_invite/zt-1gq6ufwsi-p0OZdW~e9UW_IA4_f1OfxA
    about: General usage questions, community discussions, and the development team are here.

  - name: ğŸ‡¨ğŸ‡³ PyPOTSå¾®ä¿¡ç¤¾åŒº (Community on WeChat)
    url: https://mp.weixin.qq.com/s/CGkirx7ODkngk6tGGANksw
    about: ä¸­æ–‡ç¤¾åŒºè®¨è®ºç¾¤ï¼Œæ¬¢è¿åŠ å…¥ï¼
