name: pypots-dev

channels:
    - conda-forge
    - pytorch
    - pyg
    - nodefaults

dependencies:
    # basic
    - conda-forge::pip
    - conda-forge::h5py
    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::sympy
    - conda-forge::python
    - conda-forge::einops
    - conda-forge::pandas
    - conda-forge::seaborn
    - conda-forge::matplotlib
    - conda-forge::tensorboard
    - conda-forge::scikit-learn
    - conda-forge::pygrinder >=0.6
    - conda-forge::tsdb >=0.6
    - pytorch::pytorch >=1.10.0
    ## Below we install the latest pypots because we need pypots-cli in it for development.
    - conda-forge::pypots

    # optional
    - pyg::pyg
    - pyg::pytorch-sparse
    - pyg::pytorch-scatter

    # test
    - conda-forge::pytest-cov
    - conda-forge::pytest-xdist

    # doc
    - conda-forge::furo
    - conda-forge::sphinx
    - conda-forge::docutils
    - conda-forge::sphinxcontrib-bibtex
    - conda-forge::sphinx-autodoc-typehints

    # dev
    - conda-forge::black
    - conda-forge::flake8
    - conda-forge::pre-commit
    - conda-forge::jupyterlab

    - pip:
        # doc
        - sphinxcontrib-gtagjs
        # hyperparameter tuning
        - nni
