name: pypots-test

channels:
    - conda-forge
    - pytorch
    - pyg
    - nodefaults

dependencies:
    # basic
    - conda-forge::python
    - conda-forge::pip
    - conda-forge::h5py
    - conda-forge::scipy
    - conda-forge::sympy
    - conda-forge::numpy
    - conda-forge::einops
    - conda-forge::pandas
    - conda-forge::seaborn
    - conda-forge::matplotlib
    - conda-forge::tensorboard
    - conda-forge::scikit-learn
    - conda-forge::tsdb >=0.6
    - conda-forge::pygrinder >=0.6
    - conda-forge::benchpots >=0.2
    - conda-forge::protobuf <=4.21.12
    - pytorch::pytorch >=1.10.0

    # optional
    - pyg::pyg
    - pyg::pytorch-sparse
    - pyg::pytorch-scatter

    # test
    - conda-forge::pytest-cov
    - conda-forge::pytest-xdist

    # doc
    - conda-forge::furo
    - conda-forge::sphinx
    - conda-forge::docutils
    - conda-forge::sphinxcontrib-bibtex
    - conda-forge::sphinx-autodoc-typehints

    # dev
    - conda-forge::black
    - conda-forge::flake8

    - pip:
        # doc
        - sphinxcontrib-gtagjs
