name: "Issue Manager"

on:
  push:
    branches:
      - temp_test_manager
  schedule:
    - cron: "0 8 * * *"
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "completed": {
                    "delay": "P14DT0H0M0S",
                    "message": "The issue was completed 14 days ago and no more new comments posted recently. Closing it now.",
                    "remove_label_on_comment": false,
                    "remove_label_on_close": false
                }
            }